whitelabelbuilder/core/urls.py
from django.urls import path

from .views import logout_view

app_name = 'core'
urlpatterns = [
    # path('profile/', cabinet_view, name='cabinet'),
    # path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

whitelabelbuilder/whitelabelbuilder/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework.routers import DefaultRouter
from whitelabelbuilder import settings
from core.views import UserViewSet
from whitelabel.views import TaskViewSet
from whitelabelbuilder import index
from django.conf.urls.static import static

router = DefaultRouter()
router.register('users', UserViewSet, base_name='user')
router.register('tasks', TaskViewSet, base_name='tasks')

urlpatterns = [
                  # path('', RedirectView.as_view(url='accounts/login')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('core.urls', namespace='core')),
                  path('social/', include('social_django.urls', namespace='social')),
                  path('api/v1/', include(router.urls)),

                  re_path(r'^$', index.index, name='index_page'),
                  re_path(r'^.*?/$', index.index),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns = [
#                       url(r'^__debug__/', include(debug_toolbar.urls)),
#                   ] + urlpatterns

whitelabelbuilder/core/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser
from django.db import models
from whitelabelbuilder import settings


class User(AbstractUser):
    comments_count = models.PositiveIntegerField(default=0)


class AuthoredMixin(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name='Автор')

    def get_author(self):
        return self.author or "UNKNOWN"

    class Meta:
        abstract = True


class DatedMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    class Meta:
        abstract = True


class PublicationMixin(models.Model):
    text = models.CharField(max_length=255, verbose_name='Текст')
    is_deleted = models.BooleanField(default=False, verbose_name='Удален')

    class Meta:
        abstract = True

whitelabelbuilder/whitelabel/models.py
import uuid

from django.db.models import UUIDField

from whitelabelbuilder import settings
from django.db import models


class Task(models.Model):
    uuid = UUIDField(default=uuid.uuid4, editable=False)
    service_id = models.PositiveIntegerField(verbose_name='Идентификатор задачи')
    title = models.CharField(max_length=255, verbose_name='Имя задачи')

    about_us = models.CharField(max_length=255, verbose_name='О ресторане')
    vk = models.CharField(max_length=255, verbose_name='Ссылка в VK')
    instagram = models.CharField(max_length=255, verbose_name='Ссылка в Instagram')
    facebook = models.CharField(max_length=255, verbose_name='Ссылка в Facebook')
    site = models.CharField(max_length=255, verbose_name='Ссылка на сайт')

    primary_color = models.CharField(max_length=7, verbose_name='Главный цвет')
    url = models.CharField(max_length=255, verbose_name='Адрес загрузки')
    is_successful = models.BooleanField(verbose_name='Признак выполнения', default=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name='Автор')

    logo = models.ImageField(upload_to='logos', blank=True, null=True)
    about_us_photo = models.ImageField(upload_to='about_us_photos', blank=True, null=True)

    def get_author(self):
        return self.author or "UNKNOWN"

    def get_title(self):
        return u'Пользователь %s назначил задачу сборки' % self.author

    def get_service_id(self):
        return self.service_id

    def get_primary_color(self):
        return self.primary_color

    def get_id(self):
        return self.id

    def get_uuid(self):
        return self.uuid

    def __str__(self):
        return u'Задача: от %s' % self.author.username

    class Meta:
        verbose_name = u'Задача'
        verbose_name_plural = u'Задачи'

whitelabelbuilder/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from rest_framework.decorators import list_route
from rest_framework.exceptions import AuthenticationFailed
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from .models import User
from .permissions import IsOwnerOrReadOnly
from .serializers import UserReadSerializer, UserEditSerializer


def logout_view(request):
    logout(request)

    return redirect("/")


# def login_view(request):
#     user = request.user
#
#     return render(request, 'core/login.html', {'user': user})
#
#
# def cabinet_view(request):
#     user = request.user
#
#     return render(request, 'core/cabinet.html', {'user': user})


class UserViewSet(ModelViewSet):
    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:
            return []
        return qs

    queryset = User.objects.all()
    serializer_class = UserReadSerializer
    permission_classes = (IsOwnerOrReadOnly, )

    def get_serializer_class(self):
        # print(self.get_object())
        serializer_class = self.serializer_class
        if self.request.method == 'POST':
            serializer_class = UserEditSerializer
        return serializer_class

    @list_route()
    def current(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            raise AuthenticationFailed()
        serializer = self.get_serializer_class()(request.user)
        return Response(serializer.data)

whitelabelbuilder/whitelabel/views.py
from rest_framework.viewsets import ModelViewSet

from whitelabel.models import Task
from whitelabel.serializers import TaskReadSerializer, TaskEditSerializer


class TaskViewSet(ModelViewSet):
    def get_queryset(self):
        qs = super().get_queryset()
        # if not self.request.user.is_authenticated:
        #     return []
        return qs

    queryset = Task.objects.all()
    serializer_class = TaskReadSerializer

    def get_serializer_class(self):
        # print(self.get_object())
        serializer_class = self.serializer_class
        if self.request.method == 'POST':
            serializer_class = TaskEditSerializer
        return serializer_class

whitelabelbuilder/core/templates/core/cabinet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cabinet</title>
</head>
<body>
{
{% if user.is_authenticated %}
    <p>
        {{ user.username }} cabinet (currently logged in)
        <br>
        <a href="{% url "core:logout" %}">logout</a>
        <br>
        <a href="/api/v1/">api</a>
        <br>
        <a href="/admin/">admin page</a>
        {#    <a href="{% url "social" %}">logout</a>#}
    </p>
{% endif %}

</body>
</html>

whitelabelbuilder/core/templates/core/login.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

<a href="{% url "social:begin" "vk-oauth2" %}">VK AUTH</a>
<div id="world"></div>
{#{% render_bundle 'app' 'js' %}#}
{% if user.is_authenticated %}
    <p>
    current user - <a href="{% url "core:cabinet" %}">{{ user.username }}</a> (<a href="{% url "core:logout" %}">logout</a>)
    </p>
{% endif %}

</body>
</html>

whitelabelbuilder/templates/index.html
{% load render_bundle from webpack_loader %}
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1, user-scalable=0, maximum-scale=1, minimum-scale=1"
    />
    <script src="{% static "js/sockjs.min.js" %}" type="text/javascript"></script>
    <script src="{% static "js/centrifuge.min.js" %}" type="text/javascript"></script>

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
    <title>White-Label</title>
</head>
<body>
<div id="root"></div>
<div class="msg_list" style="width: 20em; position:absolute; top: 1em; right: 1em">
    <div id="centrifuge" style="display:none"
         data-url="{{ CENTRIFUGE_WS_ENDPOINT }}"
         data-user="{{ CENTRIFUGE_USER }}"
         data-info="{{ CENTRIFUGE_INFO|safe }}"
         data-timestamp="{{ CENTRIFUGE_TIMESTAMP }}"
         data-token="{{ CENTRIFUGE_TOKEN }}"
    ></div>

    {% render_bundle 'index' 'js' %}

</body>
</html>